encoding 1251
in_file "Разрез"
out_file "разрез123"
label_text "1"
WidthOffset1 12.000000
WidthOffset2 12.000000
LengthOffset 11.500000
ArrowLength 0.000000
ArrowWidth 0.000000
CutLineSide 0
line_colour 153
text_colour 158
fit_symbol 0
aSectionMarkA1 "<< Метка >>"
aSectionMarkA2 ""
aSectionMarkA3 ""
aSectionMarkA4 ""
aSectionMarkA5 ""
SectionMarkLeftSymbolIndex 1000
SectionMarkLeftSymbolSize 12.000000
SectionMarkRightSymbolIndex 1000
SectionMarkRightSymbolSize 12.000000
SectionMarkSymbolColor 153
SectionMarkLeftSymbolPositionX 1.000000
SectionMarkLeftSymbolPositionY 0.700000
SectionMarkRightSymbolPositionX -1.000000
SectionMarkRightSymbolPositionY 0.700000
aViewLabelMarkA1 "<< Метка >>"
aViewLabelMarkA2 ""
aViewLabelMarkA3 ""
aViewLabelMarkA4 ""
aViewLabelMarkA5 ""
ViewLabelMarkSymbolIndex 0
ViewLabelMarkSymbolColor 161
ViewLabelMarkSymbolSize 5.000000
ViewLabelMarkSymbolPositionX 0.000000
ViewLabelMarkSymbolPositionY 0.000000
ViewLabelPosition 0
ViewLabelCustomLength 0.000000
ViewLabelLineLengthType 0
ViewLabelHorizontalPosition 0
SectionMarkA1_en 1
SectionMarkA2_en 1
SectionMarkA3_en 1
SectionMarkA4_en 1
SectionMarkA5_en 1
ViewMarkA1_en 1
ViewMarkA2_en 1
ViewMarkA3_en 1
ViewMarkA4_en 1
ViewMarkA5_en 1
LengthOffset_en 1
WidthOffset1_en 1
WidthOffset2_en 1
ArrowLength_en 1
ArrowWidth_en 1
line_colour_en 1
text_colour_en 1
label_en 1
CutLineSide_en 1
SectionMarkLeftSymbol_en 1
SectionMarkLeftSymbolSize_en 1
SectionMarkRightSymbol_en 1
SectionMarkRightSymbolSize_en 1
ViewLabelMarkSymbolColor_en 1
ViewLabelMarkSymbolSize_en 1
ViewLabelPosition_en 1
ViewLabelMarkSymbolIndex_en 1
SectionMarkLeftSymbolPos_en 1
SectionMarkRightSymbolPos_en 1
ViewLabelMarkSymbolPosX_en 1
ViewLabelMarkSymbolPosY_en 1
SectionMarkLeftSymbolIndex_en 1
SectionMarkRightSymbolIndex_en 1
SectionMarkSymbolColor_en 1
ViewLabelLineLength_en 1
ViewLabelHorizontalPosition_en 1
SectionMarkA1.aInFile "standard"
SectionMarkA1.aOutFile "standard"
SectionMarkA1.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="NAME" value="" subType="81"><Format font="GOST type A" color="155" height="3.500" hidden="0" override="1"/></Element></MarkPart></Mark>"
SectionMarkA1.ShowOn 0
SectionMarkA1.TextPosition 0
SectionMarkA1.TextRotation 1
SectionMarkA1.HorizontalOffset 0.000000
SectionMarkA1.VerticalOffset 0.000000
SectionMarkA1.Alignment 1
SectionMarkA1.Content_en 1
SectionMarkA1.ShowOn_en 1
SectionMarkA1.TextPosition_en 1
SectionMarkA1.HorizontalOffset_en 1
SectionMarkA1.VerticalOffset_en 1
SectionMarkA1.TextRotation_en 1
SectionMarkA1.Alignment_en 1
SectionMarkA1.FontAttr.font_name "GOST type A"
SectionMarkA1.FontAttr.text_colour 153
SectionMarkA1.FontAttr.height 3.500000
SectionMarkA1.FontAttr.font_enable 1
SectionMarkA1.FontAttr.text_colour_enable 1
SectionMarkA1.FontAttr.height_enable 1
SectionMarkA1.FrameAttr.frame_type 1
SectionMarkA1.FrameAttr.line_colour 153
SectionMarkA1.FrameAttr.frame_enable 1
SectionMarkA1.FrameAttr.line_colour_enable 1
SectionMarkA2.aInFile ""
SectionMarkA2.aOutFile ""
SectionMarkA2.ContentString ""
SectionMarkA2.ShowOn 1
SectionMarkA2.TextPosition 1
SectionMarkA2.TextRotation 1
SectionMarkA2.HorizontalOffset 0.000000
SectionMarkA2.VerticalOffset 0.000000
SectionMarkA2.Alignment 1
SectionMarkA2.Content_en 1
SectionMarkA2.ShowOn_en 1
SectionMarkA2.TextPosition_en 1
SectionMarkA2.HorizontalOffset_en 1
SectionMarkA2.VerticalOffset_en 1
SectionMarkA2.TextRotation_en 1
SectionMarkA2.Alignment_en 1
SectionMarkA2.FontAttr.font_name "Arial"
SectionMarkA2.FontAttr.text_colour 155
SectionMarkA2.FontAttr.height 3.000000
SectionMarkA2.FontAttr.font_enable 1
SectionMarkA2.FontAttr.text_colour_enable 1
SectionMarkA2.FontAttr.height_enable 1
SectionMarkA2.FrameAttr.frame_type 1
SectionMarkA2.FrameAttr.line_colour 155
SectionMarkA2.FrameAttr.frame_enable 1
SectionMarkA2.FrameAttr.line_colour_enable 1
SectionMarkA3.aInFile ""
SectionMarkA3.aOutFile ""
SectionMarkA3.ContentString ""
SectionMarkA3.ShowOn 0
SectionMarkA3.TextPosition 3
SectionMarkA3.TextRotation 0
SectionMarkA3.HorizontalOffset 0.000000
SectionMarkA3.VerticalOffset 0.000000
SectionMarkA3.Alignment 1
SectionMarkA3.Content_en 1
SectionMarkA3.ShowOn_en 1
SectionMarkA3.TextPosition_en 1
SectionMarkA3.HorizontalOffset_en 1
SectionMarkA3.VerticalOffset_en 1
SectionMarkA3.TextRotation_en 1
SectionMarkA3.Alignment_en 1
SectionMarkA3.FontAttr.font_name "romsim"
SectionMarkA3.FontAttr.text_colour 155
SectionMarkA3.FontAttr.height 2.500000
SectionMarkA3.FontAttr.font_enable 1
SectionMarkA3.FontAttr.text_colour_enable 1
SectionMarkA3.FontAttr.height_enable 1
SectionMarkA3.FrameAttr.frame_type 1
SectionMarkA3.FrameAttr.line_colour 155
SectionMarkA3.FrameAttr.frame_enable 1
SectionMarkA3.FrameAttr.line_colour_enable 1
SectionMarkA4.aInFile ""
SectionMarkA4.aOutFile ""
SectionMarkA4.ContentString ""
SectionMarkA4.ShowOn 0
SectionMarkA4.TextPosition 4
SectionMarkA4.TextRotation 0
SectionMarkA4.HorizontalOffset 0.000000
SectionMarkA4.VerticalOffset 0.000000
SectionMarkA4.Alignment 1
SectionMarkA4.Content_en 1
SectionMarkA4.ShowOn_en 1
SectionMarkA4.TextPosition_en 1
SectionMarkA4.HorizontalOffset_en 1
SectionMarkA4.VerticalOffset_en 1
SectionMarkA4.TextRotation_en 1
SectionMarkA4.Alignment_en 1
SectionMarkA4.FontAttr.font_name "romsim"
SectionMarkA4.FontAttr.text_colour 155
SectionMarkA4.FontAttr.height 2.500000
SectionMarkA4.FontAttr.font_enable 1
SectionMarkA4.FontAttr.text_colour_enable 1
SectionMarkA4.FontAttr.height_enable 1
SectionMarkA4.FrameAttr.frame_type 1
SectionMarkA4.FrameAttr.line_colour 155
SectionMarkA4.FrameAttr.frame_enable 1
SectionMarkA4.FrameAttr.line_colour_enable 1
SectionMarkA5.aInFile ""
SectionMarkA5.aOutFile ""
SectionMarkA5.ContentString ""
SectionMarkA5.ShowOn 0
SectionMarkA5.TextPosition 5
SectionMarkA5.TextRotation 0
SectionMarkA5.HorizontalOffset 10.000000
SectionMarkA5.VerticalOffset 0.000000
SectionMarkA5.Alignment 1
SectionMarkA5.Content_en 1
SectionMarkA5.ShowOn_en 1
SectionMarkA5.TextPosition_en 1
SectionMarkA5.HorizontalOffset_en 1
SectionMarkA5.VerticalOffset_en 1
SectionMarkA5.TextRotation_en 1
SectionMarkA5.Alignment_en 1
SectionMarkA5.FontAttr.font_name "romsim"
SectionMarkA5.FontAttr.text_colour 155
SectionMarkA5.FontAttr.height 2.500000
SectionMarkA5.FontAttr.font_enable 1
SectionMarkA5.FontAttr.text_colour_enable 1
SectionMarkA5.FontAttr.height_enable 1
SectionMarkA5.FrameAttr.frame_type 1
SectionMarkA5.FrameAttr.line_colour 155
SectionMarkA5.FrameAttr.frame_enable 1
SectionMarkA5.FrameAttr.line_colour_enable 1
ViewLabelMarkA1.aInFile "разрез"
ViewLabelMarkA1.aOutFile "разрез"
ViewLabelMarkA1.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="NAME" value="" subType="81"><Format font="GOST type A" color="155" height="5.000" hidden="0" override="1"/></Element></MarkPart><MarkPart groupid="0"><UserText>-<Format font="GOST type A" color="155" height="5.000" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><Element name="NAME" value="" subType="81"><Format font="GOST type A" color="155" height="5.000" hidden="0" override="1"/></Element></MarkPart></Mark>"
ViewLabelMarkA1.ShowOn 0
ViewLabelMarkA1.TextPosition 0
ViewLabelMarkA1.TextRotation 0
ViewLabelMarkA1.HorizontalOffset 0.000000
ViewLabelMarkA1.VerticalOffset 0.000000
ViewLabelMarkA1.Alignment 1
ViewLabelMarkA1.Content_en 1
ViewLabelMarkA1.ShowOn_en 1
ViewLabelMarkA1.TextPosition_en 1
ViewLabelMarkA1.HorizontalOffset_en 1
ViewLabelMarkA1.VerticalOffset_en 1
ViewLabelMarkA1.TextRotation_en 1
ViewLabelMarkA1.Alignment_en 1
ViewLabelMarkA1.FontAttr.font_name "GOST type A"
ViewLabelMarkA1.FontAttr.text_colour 155
ViewLabelMarkA1.FontAttr.height 5.000000
ViewLabelMarkA1.FontAttr.font_enable 1
ViewLabelMarkA1.FontAttr.text_colour_enable 1
ViewLabelMarkA1.FontAttr.height_enable 1
ViewLabelMarkA1.FrameAttr.frame_type 1
ViewLabelMarkA1.FrameAttr.line_colour 155
ViewLabelMarkA1.FrameAttr.frame_enable 1
ViewLabelMarkA1.FrameAttr.line_colour_enable 1
ViewLabelMarkA2.aInFile "standard"
ViewLabelMarkA2.aOutFile "standard"
ViewLabelMarkA2.ContentString ""
ViewLabelMarkA2.ShowOn 0
ViewLabelMarkA2.TextPosition 1
ViewLabelMarkA2.TextRotation 0
ViewLabelMarkA2.HorizontalOffset 0.000000
ViewLabelMarkA2.VerticalOffset 0.000000
ViewLabelMarkA2.Alignment 1
ViewLabelMarkA2.Content_en 1
ViewLabelMarkA2.ShowOn_en 1
ViewLabelMarkA2.TextPosition_en 1
ViewLabelMarkA2.HorizontalOffset_en 1
ViewLabelMarkA2.VerticalOffset_en 1
ViewLabelMarkA2.TextRotation_en 1
ViewLabelMarkA2.Alignment_en 1
ViewLabelMarkA2.FontAttr.font_name "GOST type A"
ViewLabelMarkA2.FontAttr.text_colour 155
ViewLabelMarkA2.FontAttr.height 3.500000
ViewLabelMarkA2.FontAttr.font_enable 1
ViewLabelMarkA2.FontAttr.text_colour_enable 1
ViewLabelMarkA2.FontAttr.height_enable 1
ViewLabelMarkA2.FrameAttr.frame_type 1
ViewLabelMarkA2.FrameAttr.line_colour 155
ViewLabelMarkA2.FrameAttr.frame_enable 1
ViewLabelMarkA2.FrameAttr.line_colour_enable 1
ViewLabelMarkA3.aInFile ""
ViewLabelMarkA3.aOutFile ""
ViewLabelMarkA3.ContentString ""
ViewLabelMarkA3.ShowOn 0
ViewLabelMarkA3.TextPosition 3
ViewLabelMarkA3.TextRotation 0
ViewLabelMarkA3.HorizontalOffset 0.000000
ViewLabelMarkA3.VerticalOffset 0.000000
ViewLabelMarkA3.Alignment 1
ViewLabelMarkA3.Content_en 1
ViewLabelMarkA3.ShowOn_en 1
ViewLabelMarkA3.TextPosition_en 1
ViewLabelMarkA3.HorizontalOffset_en 1
ViewLabelMarkA3.VerticalOffset_en 1
ViewLabelMarkA3.TextRotation_en 1
ViewLabelMarkA3.Alignment_en 1
ViewLabelMarkA3.FontAttr.font_name "romsim"
ViewLabelMarkA3.FontAttr.text_colour 155
ViewLabelMarkA3.FontAttr.height 2.500000
ViewLabelMarkA3.FontAttr.font_enable 1
ViewLabelMarkA3.FontAttr.text_colour_enable 1
ViewLabelMarkA3.FontAttr.height_enable 1
ViewLabelMarkA3.FrameAttr.frame_type 1
ViewLabelMarkA3.FrameAttr.line_colour 155
ViewLabelMarkA3.FrameAttr.frame_enable 1
ViewLabelMarkA3.FrameAttr.line_colour_enable 1
ViewLabelMarkA4.aInFile ""
ViewLabelMarkA4.aOutFile ""
ViewLabelMarkA4.ContentString ""
ViewLabelMarkA4.ShowOn 0
ViewLabelMarkA4.TextPosition 4
ViewLabelMarkA4.TextRotation 0
ViewLabelMarkA4.HorizontalOffset 0.000000
ViewLabelMarkA4.VerticalOffset 0.000000
ViewLabelMarkA4.Alignment 1
ViewLabelMarkA4.Content_en 1
ViewLabelMarkA4.ShowOn_en 1
ViewLabelMarkA4.TextPosition_en 1
ViewLabelMarkA4.HorizontalOffset_en 1
ViewLabelMarkA4.VerticalOffset_en 1
ViewLabelMarkA4.TextRotation_en 1
ViewLabelMarkA4.Alignment_en 1
ViewLabelMarkA4.FontAttr.font_name "romsim"
ViewLabelMarkA4.FontAttr.text_colour 155
ViewLabelMarkA4.FontAttr.height 2.500000
ViewLabelMarkA4.FontAttr.font_enable 1
ViewLabelMarkA4.FontAttr.text_colour_enable 1
ViewLabelMarkA4.FontAttr.height_enable 1
ViewLabelMarkA4.FrameAttr.frame_type 1
ViewLabelMarkA4.FrameAttr.line_colour 155
ViewLabelMarkA4.FrameAttr.frame_enable 1
ViewLabelMarkA4.FrameAttr.line_colour_enable 1
ViewLabelMarkA5.aInFile ""
ViewLabelMarkA5.aOutFile ""
ViewLabelMarkA5.ContentString ""
ViewLabelMarkA5.ShowOn 0
ViewLabelMarkA5.TextPosition 5
ViewLabelMarkA5.TextRotation 0
ViewLabelMarkA5.HorizontalOffset 10.000000
ViewLabelMarkA5.VerticalOffset 0.000000
ViewLabelMarkA5.Alignment 1
ViewLabelMarkA5.Content_en 1
ViewLabelMarkA5.ShowOn_en 1
ViewLabelMarkA5.TextPosition_en 1
ViewLabelMarkA5.HorizontalOffset_en 1
ViewLabelMarkA5.VerticalOffset_en 1
ViewLabelMarkA5.TextRotation_en 1
ViewLabelMarkA5.Alignment_en 1
ViewLabelMarkA5.FontAttr.font_name "romsim"
ViewLabelMarkA5.FontAttr.text_colour 155
ViewLabelMarkA5.FontAttr.height 2.500000
ViewLabelMarkA5.FontAttr.font_enable 1
ViewLabelMarkA5.FontAttr.text_colour_enable 1
ViewLabelMarkA5.FontAttr.height_enable 1
ViewLabelMarkA5.FrameAttr.frame_type 1
ViewLabelMarkA5.FrameAttr.line_colour 155
ViewLabelMarkA5.FrameAttr.frame_enable 1
ViewLabelMarkA5.FrameAttr.line_colour_enable 1
